    /*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controlador.ProyectoESport;
import ModeloUML.Equipo;
import ModeloUML.Partido;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author 1gdaw03
 */
public class Clasificaciones extends javax.swing.JFrame {

    /**
     * Creates new form Clasificaciones
     */
    public Clasificaciones() {
        initComponents();
        rellenarDatos();
        E1.setEditable(false);
        E2.setEditable(false);
        E3.setEditable(false);
        E4.setEditable(false);
        E5.setEditable(false);
        E6.setEditable(false);
        E7.setEditable(false);
        E8.setEditable(false);        
        PT1.setEditable(false);
        PT2.setEditable(false);
        PT3.setEditable(false);
        PT4.setEditable(false);
        PT5.setEditable(false);
        PT6.setEditable(false);
        PT7.setEditable(false);
        PT8.setEditable(false);        
        PJT1.setEditable(false);
        PJT2.setEditable(false);
        PJT3.setEditable(false);
        PJT4.setEditable(false);
        PJT5.setEditable(false);
        PJT6.setEditable(false);
        PJT7.setEditable(false);
        PJT8.setEditable(false);        
        PGT1.setEditable(false);
        PGT2.setEditable(false);
        PGT3.setEditable(false);
        PGT4.setEditable(false);
        PGT5.setEditable(false);
        PGT6.setEditable(false);
        PGT7.setEditable(false);
        PGT8.setEditable(false);        
        PPT1.setEditable(false);
        PPT2.setEditable(false);
        PPT3.setEditable(false);
        PPT4.setEditable(false);
        PPT5.setEditable(false);
        PPT6.setEditable(false);
        PPT7.setEditable(false);
        PPT8.setEditable(false);        
        PL1.setEditable(false);
        PL2.setEditable(false);
        PL3.setEditable(false);
        PL4.setEditable(false);
        PL5.setEditable(false);
        PL6.setEditable(false);
        PL7.setEditable(false);
        PL8.setEditable(false);      
        PJL1.setEditable(false);
        PJL2.setEditable(false);
        PJL3.setEditable(false);
        PJL4.setEditable(false);
        PJL5.setEditable(false);
        PJL6.setEditable(false);
        PJL7.setEditable(false);
        PJL8.setEditable(false);       
        PGL1.setEditable(false);
        PGL2.setEditable(false);
        PGL3.setEditable(false);
        PGL4.setEditable(false);
        PGL5.setEditable(false);
        PGL6.setEditable(false);
        PGL7.setEditable(false);
        PGL8.setEditable(false);       
        PV1.setEditable(false);
        PV2.setEditable(false);
        PV3.setEditable(false);
        PV4.setEditable(false);
        PV5.setEditable(false);
        PV6.setEditable(false);
        PV7.setEditable(false);
        PV8.setEditable(false);       
        PPL1.setEditable(false);
        PPL2.setEditable(false);
        PPL3.setEditable(false);
        PPL4.setEditable(false);
        PPL5.setEditable(false);
        PPL6.setEditable(false);
        PPL7.setEditable(false);
        PPL8.setEditable(false);       
        PJV1.setEditable(false);
        PJV2.setEditable(false);
        PJV3.setEditable(false);
        PJV4.setEditable(false);
        PJV5.setEditable(false);
        PJV6.setEditable(false);
        PJV7.setEditable(false);
        PJV8.setEditable(false);       
        PGV1.setEditable(false);
        PGV2.setEditable(false);
        PGV3.setEditable(false);
        PGV4.setEditable(false);
        PGV5.setEditable(false);
        PGV6.setEditable(false);
        PGV7.setEditable(false);
        PGV8.setEditable(false);       
        PPV1.setEditable(false);
        PPV2.setEditable(false);
        PPV3.setEditable(false);
        PPV4.setEditable(false);
        PPV5.setEditable(false);
        PPV6.setEditable(false);
        PPV7.setEditable(false);
        PPV8.setEditable(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        E1 = new javax.swing.JTextField();
        E2 = new javax.swing.JTextField();
        E3 = new javax.swing.JTextField();
        E4 = new javax.swing.JTextField();
        E5 = new javax.swing.JTextField();
        E6 = new javax.swing.JTextField();
        E7 = new javax.swing.JTextField();
        E8 = new javax.swing.JTextField();
        PT1 = new javax.swing.JTextField();
        PT2 = new javax.swing.JTextField();
        PT3 = new javax.swing.JTextField();
        PT4 = new javax.swing.JTextField();
        PT5 = new javax.swing.JTextField();
        PT6 = new javax.swing.JTextField();
        PT7 = new javax.swing.JTextField();
        PT8 = new javax.swing.JTextField();
        PJT1 = new javax.swing.JTextField();
        PJT2 = new javax.swing.JTextField();
        PJT3 = new javax.swing.JTextField();
        PJT4 = new javax.swing.JTextField();
        PJT5 = new javax.swing.JTextField();
        PJT6 = new javax.swing.JTextField();
        PJT7 = new javax.swing.JTextField();
        PJT8 = new javax.swing.JTextField();
        PGT1 = new javax.swing.JTextField();
        PGT2 = new javax.swing.JTextField();
        PGT3 = new javax.swing.JTextField();
        PGT4 = new javax.swing.JTextField();
        PGT5 = new javax.swing.JTextField();
        PGT6 = new javax.swing.JTextField();
        PGT7 = new javax.swing.JTextField();
        PGT8 = new javax.swing.JTextField();
        PPT1 = new javax.swing.JTextField();
        PPT2 = new javax.swing.JTextField();
        PPT3 = new javax.swing.JTextField();
        PPT4 = new javax.swing.JTextField();
        PPT5 = new javax.swing.JTextField();
        PPT6 = new javax.swing.JTextField();
        PPT7 = new javax.swing.JTextField();
        PPT8 = new javax.swing.JTextField();
        PL1 = new javax.swing.JTextField();
        PL2 = new javax.swing.JTextField();
        PL3 = new javax.swing.JTextField();
        PL4 = new javax.swing.JTextField();
        PL5 = new javax.swing.JTextField();
        PL6 = new javax.swing.JTextField();
        PL7 = new javax.swing.JTextField();
        PL8 = new javax.swing.JTextField();
        PJL1 = new javax.swing.JTextField();
        PJL2 = new javax.swing.JTextField();
        PJL3 = new javax.swing.JTextField();
        PJL4 = new javax.swing.JTextField();
        PJL5 = new javax.swing.JTextField();
        PJL6 = new javax.swing.JTextField();
        PJL7 = new javax.swing.JTextField();
        PJL8 = new javax.swing.JTextField();
        PGL1 = new javax.swing.JTextField();
        PGL2 = new javax.swing.JTextField();
        PGL3 = new javax.swing.JTextField();
        PGL4 = new javax.swing.JTextField();
        PGL5 = new javax.swing.JTextField();
        PGL6 = new javax.swing.JTextField();
        PGL7 = new javax.swing.JTextField();
        PGL8 = new javax.swing.JTextField();
        PPL1 = new javax.swing.JTextField();
        PPL2 = new javax.swing.JTextField();
        PPL3 = new javax.swing.JTextField();
        PPL4 = new javax.swing.JTextField();
        PPL5 = new javax.swing.JTextField();
        PPL6 = new javax.swing.JTextField();
        PPL7 = new javax.swing.JTextField();
        PPL8 = new javax.swing.JTextField();
        PV1 = new javax.swing.JTextField();
        PV2 = new javax.swing.JTextField();
        PV3 = new javax.swing.JTextField();
        PV4 = new javax.swing.JTextField();
        PV5 = new javax.swing.JTextField();
        PV6 = new javax.swing.JTextField();
        PV7 = new javax.swing.JTextField();
        PV8 = new javax.swing.JTextField();
        PJV1 = new javax.swing.JTextField();
        PJV2 = new javax.swing.JTextField();
        PJV3 = new javax.swing.JTextField();
        PJV4 = new javax.swing.JTextField();
        PJV5 = new javax.swing.JTextField();
        PJV6 = new javax.swing.JTextField();
        PJV7 = new javax.swing.JTextField();
        PJV8 = new javax.swing.JTextField();
        PGV1 = new javax.swing.JTextField();
        PGV2 = new javax.swing.JTextField();
        PGV3 = new javax.swing.JTextField();
        PGV4 = new javax.swing.JTextField();
        PGV5 = new javax.swing.JTextField();
        PGV6 = new javax.swing.JTextField();
        PGV7 = new javax.swing.JTextField();
        PGV8 = new javax.swing.JTextField();
        PPV1 = new javax.swing.JTextField();
        PPV2 = new javax.swing.JTextField();
        PPV3 = new javax.swing.JTextField();
        PPV4 = new javax.swing.JTextField();
        PPV5 = new javax.swing.JTextField();
        PPV6 = new javax.swing.JTextField();
        PPV7 = new javax.swing.JTextField();
        PPV8 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        bVolver = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        E1.setBackground(new java.awt.Color(255, 255, 255));
        E1.setBorder(null);
        getContentPane().add(E1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 170, 270, 50));

        E2.setBackground(new java.awt.Color(255, 255, 255));
        E2.setBorder(null);
        getContentPane().add(E2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 230, 270, 50));

        E3.setBackground(new java.awt.Color(255, 255, 255));
        E3.setBorder(null);
        getContentPane().add(E3, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 300, 270, 50));

        E4.setBackground(new java.awt.Color(255, 255, 255));
        E4.setBorder(null);
        getContentPane().add(E4, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 370, 270, 50));

        E5.setBackground(new java.awt.Color(255, 255, 255));
        E5.setBorder(null);
        getContentPane().add(E5, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 440, 270, 50));

        E6.setBackground(new java.awt.Color(255, 255, 255));
        E6.setBorder(null);
        getContentPane().add(E6, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 500, 270, 50));

        E7.setBackground(new java.awt.Color(255, 255, 255));
        E7.setBorder(null);
        getContentPane().add(E7, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 570, 270, 50));

        E8.setBackground(new java.awt.Color(255, 255, 255));
        E8.setBorder(null);
        getContentPane().add(E8, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 640, 270, 50));

        PT1.setBackground(new java.awt.Color(177, 107, 255));
        PT1.setBorder(null);
        getContentPane().add(PT1, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 170, 60, 50));

        PT2.setBackground(new java.awt.Color(177, 107, 255));
        PT2.setBorder(null);
        getContentPane().add(PT2, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 230, 60, 50));

        PT3.setBackground(new java.awt.Color(177, 107, 255));
        PT3.setBorder(null);
        getContentPane().add(PT3, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 300, 60, 50));

        PT4.setBackground(new java.awt.Color(177, 107, 255));
        PT4.setBorder(null);
        getContentPane().add(PT4, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 370, 60, 50));

        PT5.setBackground(new java.awt.Color(177, 107, 255));
        PT5.setBorder(null);
        getContentPane().add(PT5, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 430, 60, 50));

        PT6.setBackground(new java.awt.Color(177, 107, 255));
        PT6.setBorder(null);
        getContentPane().add(PT6, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 500, 60, 50));

        PT7.setBackground(new java.awt.Color(177, 107, 255));
        PT7.setBorder(null);
        getContentPane().add(PT7, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 570, 60, 50));

        PT8.setBackground(new java.awt.Color(177, 107, 255));
        PT8.setBorder(null);
        getContentPane().add(PT8, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 640, 60, 50));

        PJT1.setBackground(new java.awt.Color(255, 255, 255));
        PJT1.setBorder(null);
        getContentPane().add(PJT1, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 170, 60, 50));

        PJT2.setBackground(new java.awt.Color(255, 255, 255));
        PJT2.setBorder(null);
        getContentPane().add(PJT2, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 230, 60, 60));

        PJT3.setBackground(new java.awt.Color(255, 255, 255));
        PJT3.setBorder(null);
        getContentPane().add(PJT3, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 300, 60, 50));

        PJT4.setBackground(new java.awt.Color(255, 255, 255));
        PJT4.setBorder(null);
        getContentPane().add(PJT4, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 370, 60, 50));

        PJT5.setBackground(new java.awt.Color(255, 255, 255));
        PJT5.setBorder(null);
        getContentPane().add(PJT5, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 430, 60, 60));

        PJT6.setBackground(new java.awt.Color(255, 255, 255));
        PJT6.setBorder(null);
        getContentPane().add(PJT6, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 500, 60, 50));

        PJT7.setBackground(new java.awt.Color(255, 255, 255));
        PJT7.setBorder(null);
        getContentPane().add(PJT7, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 570, 60, 50));

        PJT8.setBackground(new java.awt.Color(255, 255, 255));
        PJT8.setBorder(null);
        getContentPane().add(PJT8, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 640, 60, 50));

        PGT1.setBackground(new java.awt.Color(255, 255, 255));
        PGT1.setBorder(null);
        getContentPane().add(PGT1, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 170, 60, 50));

        PGT2.setBackground(new java.awt.Color(255, 255, 255));
        PGT2.setBorder(null);
        getContentPane().add(PGT2, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 230, 60, 50));

        PGT3.setBackground(new java.awt.Color(255, 255, 255));
        PGT3.setBorder(null);
        getContentPane().add(PGT3, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 300, 60, 50));

        PGT4.setBackground(new java.awt.Color(255, 255, 255));
        PGT4.setBorder(null);
        getContentPane().add(PGT4, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 370, 60, 50));

        PGT5.setBackground(new java.awt.Color(255, 255, 255));
        PGT5.setBorder(null);
        getContentPane().add(PGT5, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 440, 60, 50));

        PGT6.setBackground(new java.awt.Color(255, 255, 255));
        PGT6.setBorder(null);
        getContentPane().add(PGT6, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 500, 60, 50));

        PGT7.setBackground(new java.awt.Color(255, 255, 255));
        PGT7.setBorder(null);
        getContentPane().add(PGT7, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 570, 60, 50));

        PGT8.setBackground(new java.awt.Color(255, 255, 255));
        PGT8.setBorder(null);
        getContentPane().add(PGT8, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 640, 60, 50));

        PPT1.setBackground(new java.awt.Color(255, 255, 255));
        PPT1.setBorder(null);
        PPT1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PPT1ActionPerformed(evt);
            }
        });
        getContentPane().add(PPT1, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 170, 60, 50));

        PPT2.setBackground(new java.awt.Color(255, 255, 255));
        PPT2.setBorder(null);
        getContentPane().add(PPT2, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 230, 60, 50));

        PPT3.setBackground(new java.awt.Color(255, 255, 255));
        PPT3.setBorder(null);
        getContentPane().add(PPT3, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 300, 60, 50));

        PPT4.setBackground(new java.awt.Color(255, 255, 255));
        PPT4.setBorder(null);
        getContentPane().add(PPT4, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 370, 60, 50));

        PPT5.setBackground(new java.awt.Color(255, 255, 255));
        PPT5.setBorder(null);
        getContentPane().add(PPT5, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 440, 60, 50));

        PPT6.setBackground(new java.awt.Color(255, 255, 255));
        PPT6.setBorder(null);
        getContentPane().add(PPT6, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 500, 60, 50));

        PPT7.setBackground(new java.awt.Color(255, 255, 255));
        PPT7.setBorder(null);
        getContentPane().add(PPT7, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 570, 60, 50));

        PPT8.setBackground(new java.awt.Color(255, 255, 255));
        PPT8.setBorder(null);
        getContentPane().add(PPT8, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 640, 60, 50));

        PL1.setBackground(new java.awt.Color(0, 102, 254));
        PL1.setBorder(null);
        getContentPane().add(PL1, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 170, 60, 50));

        PL2.setBackground(new java.awt.Color(0, 102, 254));
        PL2.setBorder(null);
        getContentPane().add(PL2, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 230, 60, 50));

        PL3.setBackground(new java.awt.Color(0, 102, 254));
        PL3.setBorder(null);
        getContentPane().add(PL3, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 300, 60, 50));

        PL4.setBackground(new java.awt.Color(0, 102, 254));
        PL4.setBorder(null);
        getContentPane().add(PL4, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 370, 60, 50));

        PL5.setBackground(new java.awt.Color(0, 102, 254));
        PL5.setBorder(null);
        getContentPane().add(PL5, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 440, 60, 50));

        PL6.setBackground(new java.awt.Color(0, 102, 254));
        PL6.setBorder(null);
        getContentPane().add(PL6, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 500, 60, 50));

        PL7.setBackground(new java.awt.Color(0, 102, 254));
        PL7.setBorder(null);
        getContentPane().add(PL7, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 570, 60, 50));

        PL8.setBackground(new java.awt.Color(0, 102, 204));
        PL8.setBorder(null);
        getContentPane().add(PL8, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 640, 60, 50));

        PJL1.setBackground(new java.awt.Color(255, 255, 255));
        PJL1.setBorder(null);
        getContentPane().add(PJL1, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 170, 60, 50));

        PJL2.setBackground(new java.awt.Color(255, 255, 255));
        PJL2.setBorder(null);
        getContentPane().add(PJL2, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 230, 60, 50));

        PJL3.setBackground(new java.awt.Color(255, 255, 255));
        PJL3.setBorder(null);
        getContentPane().add(PJL3, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 300, 60, 50));

        PJL4.setBackground(new java.awt.Color(255, 255, 255));
        PJL4.setBorder(null);
        getContentPane().add(PJL4, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 370, 60, 50));

        PJL5.setBackground(new java.awt.Color(255, 255, 255));
        PJL5.setBorder(null);
        getContentPane().add(PJL5, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 440, 60, 50));

        PJL6.setBackground(new java.awt.Color(255, 255, 255));
        PJL6.setBorder(null);
        getContentPane().add(PJL6, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 500, 60, 50));

        PJL7.setBackground(new java.awt.Color(255, 255, 255));
        PJL7.setBorder(null);
        getContentPane().add(PJL7, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 570, 60, 50));

        PJL8.setBackground(new java.awt.Color(255, 255, 255));
        PJL8.setBorder(null);
        getContentPane().add(PJL8, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 640, 60, 50));

        PGL1.setBackground(new java.awt.Color(255, 255, 255));
        PGL1.setBorder(null);
        getContentPane().add(PGL1, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 170, 60, 50));

        PGL2.setBackground(new java.awt.Color(255, 255, 255));
        PGL2.setBorder(null);
        getContentPane().add(PGL2, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 230, 60, 50));

        PGL3.setBackground(new java.awt.Color(255, 255, 255));
        PGL3.setBorder(null);
        getContentPane().add(PGL3, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 300, 60, 50));

        PGL4.setBackground(new java.awt.Color(255, 255, 255));
        PGL4.setBorder(null);
        getContentPane().add(PGL4, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 370, 60, 50));

        PGL5.setBackground(new java.awt.Color(255, 255, 255));
        PGL5.setBorder(null);
        getContentPane().add(PGL5, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 430, 60, 50));

        PGL6.setBackground(new java.awt.Color(255, 255, 255));
        PGL6.setBorder(null);
        getContentPane().add(PGL6, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 500, 60, 50));

        PGL7.setBackground(new java.awt.Color(255, 255, 255));
        PGL7.setBorder(null);
        getContentPane().add(PGL7, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 570, 60, 50));

        PGL8.setBackground(new java.awt.Color(255, 255, 255));
        PGL8.setBorder(null);
        getContentPane().add(PGL8, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 640, 60, 50));

        PPL1.setBackground(new java.awt.Color(255, 255, 255));
        PPL1.setBorder(null);
        getContentPane().add(PPL1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 170, 60, 50));

        PPL2.setBackground(new java.awt.Color(255, 255, 255));
        PPL2.setBorder(null);
        getContentPane().add(PPL2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 230, 60, 50));

        PPL3.setBackground(new java.awt.Color(255, 255, 255));
        PPL3.setBorder(null);
        getContentPane().add(PPL3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 300, 60, 50));

        PPL4.setBackground(new java.awt.Color(255, 255, 255));
        PPL4.setBorder(null);
        getContentPane().add(PPL4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 370, 60, 50));

        PPL5.setBackground(new java.awt.Color(255, 255, 255));
        PPL5.setBorder(null);
        getContentPane().add(PPL5, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 440, 60, 50));

        PPL6.setBackground(new java.awt.Color(255, 255, 255));
        PPL6.setBorder(null);
        getContentPane().add(PPL6, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 500, 60, 50));

        PPL7.setBackground(new java.awt.Color(255, 255, 255));
        PPL7.setBorder(null);
        getContentPane().add(PPL7, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 570, 60, 50));

        PPL8.setBackground(new java.awt.Color(255, 255, 255));
        PPL8.setBorder(null);
        getContentPane().add(PPL8, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 640, 60, 50));

        PV1.setBackground(new java.awt.Color(202, 46, 46));
        PV1.setBorder(null);
        getContentPane().add(PV1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 170, 60, 50));

        PV2.setBackground(new java.awt.Color(202, 46, 46));
        PV2.setBorder(null);
        getContentPane().add(PV2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 240, 60, 50));

        PV3.setBackground(new java.awt.Color(202, 46, 46));
        PV3.setBorder(null);
        getContentPane().add(PV3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 300, 60, 50));

        PV4.setBackground(new java.awt.Color(202, 46, 46));
        PV4.setBorder(null);
        getContentPane().add(PV4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 370, 60, 50));

        PV5.setBackground(new java.awt.Color(202, 46, 46));
        PV5.setBorder(null);
        getContentPane().add(PV5, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 440, 60, 50));

        PV6.setBackground(new java.awt.Color(202, 46, 46));
        PV6.setBorder(null);
        getContentPane().add(PV6, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 500, 60, 50));

        PV7.setBackground(new java.awt.Color(202, 46, 46));
        PV7.setBorder(null);
        getContentPane().add(PV7, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 570, 60, 50));

        PV8.setBackground(new java.awt.Color(202, 46, 46));
        PV8.setBorder(null);
        getContentPane().add(PV8, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 640, 60, 50));

        PJV1.setBackground(new java.awt.Color(255, 255, 255));
        PJV1.setBorder(null);
        getContentPane().add(PJV1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1160, 170, 60, 50));

        PJV2.setBackground(new java.awt.Color(255, 255, 255));
        PJV2.setBorder(null);
        getContentPane().add(PJV2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1160, 230, 60, 50));

        PJV3.setBackground(new java.awt.Color(255, 255, 255));
        PJV3.setBorder(null);
        getContentPane().add(PJV3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1160, 300, 60, 50));

        PJV4.setBackground(new java.awt.Color(255, 255, 255));
        PJV4.setBorder(null);
        getContentPane().add(PJV4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1160, 370, 60, 50));

        PJV5.setBackground(new java.awt.Color(255, 255, 255));
        PJV5.setBorder(null);
        getContentPane().add(PJV5, new org.netbeans.lib.awtextra.AbsoluteConstraints(1160, 440, 60, 50));

        PJV6.setBackground(new java.awt.Color(255, 255, 255));
        PJV6.setBorder(null);
        getContentPane().add(PJV6, new org.netbeans.lib.awtextra.AbsoluteConstraints(1160, 500, 60, 50));

        PJV7.setBackground(new java.awt.Color(255, 255, 255));
        PJV7.setBorder(null);
        getContentPane().add(PJV7, new org.netbeans.lib.awtextra.AbsoluteConstraints(1160, 570, 60, 50));

        PJV8.setBackground(new java.awt.Color(255, 255, 255));
        PJV8.setBorder(null);
        getContentPane().add(PJV8, new org.netbeans.lib.awtextra.AbsoluteConstraints(1160, 640, 60, 50));

        PGV1.setBackground(new java.awt.Color(255, 255, 255));
        PGV1.setBorder(null);
        getContentPane().add(PGV1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1240, 170, 60, 50));

        PGV2.setBackground(new java.awt.Color(255, 255, 255));
        PGV2.setBorder(null);
        getContentPane().add(PGV2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1240, 230, 60, 50));

        PGV3.setBackground(new java.awt.Color(255, 255, 255));
        PGV3.setBorder(null);
        getContentPane().add(PGV3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1240, 300, 60, 50));

        PGV4.setBackground(new java.awt.Color(255, 255, 255));
        PGV4.setBorder(null);
        getContentPane().add(PGV4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1240, 370, 60, 50));

        PGV5.setBackground(new java.awt.Color(255, 255, 255));
        PGV5.setBorder(null);
        getContentPane().add(PGV5, new org.netbeans.lib.awtextra.AbsoluteConstraints(1240, 440, 60, 50));

        PGV6.setBackground(new java.awt.Color(255, 255, 255));
        PGV6.setBorder(null);
        getContentPane().add(PGV6, new org.netbeans.lib.awtextra.AbsoluteConstraints(1240, 500, 60, 50));

        PGV7.setBackground(new java.awt.Color(255, 255, 255));
        PGV7.setBorder(null);
        getContentPane().add(PGV7, new org.netbeans.lib.awtextra.AbsoluteConstraints(1240, 570, 60, 50));

        PGV8.setBackground(new java.awt.Color(255, 255, 255));
        PGV8.setBorder(null);
        getContentPane().add(PGV8, new org.netbeans.lib.awtextra.AbsoluteConstraints(1240, 640, 60, 50));

        PPV1.setBackground(new java.awt.Color(255, 255, 255));
        PPV1.setBorder(null);
        getContentPane().add(PPV1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1310, 170, 60, 50));

        PPV2.setBackground(new java.awt.Color(255, 255, 255));
        PPV2.setBorder(null);
        getContentPane().add(PPV2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1310, 240, 60, 50));

        PPV3.setBackground(new java.awt.Color(255, 255, 255));
        PPV3.setBorder(null);
        getContentPane().add(PPV3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1310, 300, 60, 50));

        PPV4.setBackground(new java.awt.Color(255, 255, 255));
        PPV4.setBorder(null);
        getContentPane().add(PPV4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1310, 370, 60, 50));

        PPV5.setBackground(new java.awt.Color(255, 255, 255));
        PPV5.setBorder(null);
        getContentPane().add(PPV5, new org.netbeans.lib.awtextra.AbsoluteConstraints(1310, 440, 60, 50));

        PPV6.setBackground(new java.awt.Color(255, 255, 255));
        PPV6.setBorder(null);
        getContentPane().add(PPV6, new org.netbeans.lib.awtextra.AbsoluteConstraints(1310, 500, 60, 50));

        PPV7.setBackground(new java.awt.Color(255, 255, 255));
        PPV7.setBorder(null);
        getContentPane().add(PPV7, new org.netbeans.lib.awtextra.AbsoluteConstraints(1310, 570, 60, 50));

        PPV8.setBackground(new java.awt.Color(255, 255, 255));
        PPV8.setBorder(null);
        getContentPane().add(PPV8, new org.netbeans.lib.awtextra.AbsoluteConstraints(1310, 640, 60, 50));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Fotos/Clasificacion.png"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 90, -1, -1));

        bVolver.setText("VOLVER");
        bVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bVolverActionPerformed(evt);
            }
        });
        getContentPane().add(bVolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 130, 50));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Clasificacion.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 90, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void PPT1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PPT1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PPT1ActionPerformed

    private void rellenarDatos(){ 
        try{
       
            int cont1=0;
            int cont2=0;
            int cont3=0;
            int cont4=0;
            int cont5=0;
            int cont6=0;
            int cont7=0;
            int cont8=0;
            int cont9=0;
            int cont10=0;
            int cont11=0;
            int cont12=0;
            int cont13=0;
            int cont14=0;
            int cont15=0;
            int cont16=0;
            int cont17=0;
            int cont18=0;
            int cont19=0;
            int cont20=0;
            int cont21=0;
            int cont22=0;
            int cont23=0;
            int cont24=0;
            int cont25=0;
            int cont26=0;
            int cont27=0;
            int cont28=0;
            int cont29=0;
            int cont30=0;
            int cont31=0;
            int cont32=0;
            int cont33=0;
            int cont34=0;
            int cont35=0;
            int cont36=0;
            int cont37=0;
            int cont38=0;
            int cont39=0;
            int cont40=0;
            int cont41=0;
            int cont42=0;
            int cont43=0;
            int cont44=0;
            int cont45=0;
            int cont46=0;
            int cont47=0;
            int cont48=0;
            
            ArrayList<Equipo> lista = ProyectoESport.seleccionarPuntosPorEquipos();
            
            E1.setText(lista.get(0).getNombre());
            PT1.setText(String.valueOf(lista.get(0).getPuntos()));
            E2.setText(lista.get(1).getNombre());
            PT2.setText(String.valueOf(lista.get(1).getPuntos()));
            E3.setText(lista.get(2).getNombre());
            PT3.setText(String.valueOf(lista.get(2).getPuntos()));
            E4.setText(lista.get(3).getNombre());
            PT4.setText(String.valueOf(lista.get(3).getPuntos()));
            E5.setText(lista.get(4).getNombre());
            PT5.setText(String.valueOf(lista.get(4).getPuntos()));
            E6.setText(lista.get(5).getNombre());
            PT6.setText(String.valueOf(lista.get(5).getPuntos()));
            E7.setText(lista.get(6).getNombre());
            PT7.setText(String.valueOf(lista.get(6).getPuntos()));
            E8.setText(lista.get(7).getNombre());
            PT8.setText(String.valueOf(lista.get(7).getPuntos()));
            
            ArrayList<Partido> lista1 = ProyectoESport.seleccionarResultadoPorLocal(lista.get(0).getId());
            ArrayList<Partido> lista2 = ProyectoESport.seleccionarResultadoPorVisitante(lista.get(0).getId());
            for(int x=0;x<ProyectoESport.seleccionarResultadoPorLocal(lista.get(0).getId()).size();x++)
            {
                cont1 =cont1 + lista1.get(x).getRes_local();
                cont2 =cont2 + lista2.get(x).getRes_visit();
                if(lista1.get(x).getRes_local()>lista1.get(x).getRes_visit())
                    cont3 =cont3 + lista1.get(x).getRes_local();
                else
                    cont4 =cont4 + lista1.get(x).getRes_visit();
                
                if(lista2.get(x).getRes_local()<lista2.get(x).getRes_visit())
                    cont5 =cont5 + lista2.get(x).getRes_visit();
                else
                    cont6 =cont6 + lista2.get(x).getRes_local();
            }    
            PJL1.setText(String.valueOf(ProyectoESport.seleccionarResultadoPorLocal(lista.get(0).getId()).size()));
            PJV1.setText(String.valueOf(ProyectoESport.seleccionarResultadoPorVisitante(lista.get(0).getId()).size()));
            PL1.setText(String.valueOf(cont1));
            PV1.setText(String.valueOf(cont2));
            PGL1.setText(String.valueOf(cont3));
            PPL1.setText(String.valueOf(cont4));
            PGV1.setText(String.valueOf(cont5));
            PPV1.setText(String.valueOf(cont6));
            
            ArrayList<Partido> lista3 = ProyectoESport.seleccionarResultadoPorLocal(lista.get(1).getId());
            ArrayList<Partido> lista4 = ProyectoESport.seleccionarResultadoPorVisitante(lista.get(1).getId());
            for(int x=0;x<ProyectoESport.seleccionarResultadoPorLocal(lista.get(1).getId()).size();x++)
            {
                cont7 =cont7 + lista3.get(x).getRes_local();
                cont8 =cont8 + lista4.get(x).getRes_visit();
                if(lista3.get(x).getRes_local()>lista3.get(x).getRes_visit())
                    cont9 =cont9 + lista3.get(x).getRes_local();
                else
                    cont10 =cont10 + lista3.get(x).getRes_visit();
                
                if(lista4.get(x).getRes_local()<lista4.get(x).getRes_visit())
                    cont11 =cont11 + lista4.get(x).getRes_visit();
                else
                    cont12 =cont12 + lista4.get(x).getRes_local();
            }    
            PJL2.setText(String.valueOf(ProyectoESport.seleccionarResultadoPorLocal(lista.get(1).getId()).size()));
            PJV2.setText(String.valueOf(ProyectoESport.seleccionarResultadoPorVisitante(lista.get(1).getId()).size()));
            PL2.setText(String.valueOf(cont7));
            PV2.setText(String.valueOf(cont8));
            PGL2.setText(String.valueOf(cont9));
            PPL2.setText(String.valueOf(cont10));
            PGV2.setText(String.valueOf(cont11));
            PPV2.setText(String.valueOf(cont12));
            
            ArrayList<Partido> lista5 = ProyectoESport.seleccionarResultadoPorLocal(lista.get(2).getId());
            ArrayList<Partido> lista6 = ProyectoESport.seleccionarResultadoPorVisitante(lista.get(2).getId());
            for(int x=0;x<ProyectoESport.seleccionarResultadoPorLocal(lista.get(2).getId()).size();x++)
            {
                cont13 =cont13 + lista5.get(x).getRes_local();
                cont14 =cont14 + lista6.get(x).getRes_visit();
                if(lista5.get(x).getRes_local()>lista5.get(x).getRes_visit())
                    cont15 =cont15 + lista5.get(x).getRes_local();
                else
                    cont16 =cont16 + lista5.get(x).getRes_visit();
                
                if(lista6.get(x).getRes_local()<lista6.get(x).getRes_visit())
                    cont17 =cont17 + lista6.get(x).getRes_visit();
                else
                    cont18 =cont18 + lista6.get(x).getRes_local();
            }    
            PJL3.setText(String.valueOf(ProyectoESport.seleccionarResultadoPorLocal(lista.get(2).getId()).size()));
            PJV3.setText(String.valueOf(ProyectoESport.seleccionarResultadoPorVisitante(lista.get(2).getId()).size()));
            PL3.setText(String.valueOf(cont13));
            PV3.setText(String.valueOf(cont14));
            PGL3.setText(String.valueOf(cont15));
            PPL3.setText(String.valueOf(cont16));
            PGV3.setText(String.valueOf(cont17));
            PPV3.setText(String.valueOf(cont18));
            
            ArrayList<Partido> lista7 = ProyectoESport.seleccionarResultadoPorLocal(lista.get(3).getId());
            ArrayList<Partido> lista8 = ProyectoESport.seleccionarResultadoPorVisitante(lista.get(3).getId());
            for(int x=0;x<ProyectoESport.seleccionarResultadoPorLocal(lista.get(3).getId()).size();x++)
            {
                cont19 =cont19 + lista7.get(x).getRes_local();
                cont20 =cont20 + lista8.get(x).getRes_visit();
                if(lista7.get(x).getRes_local()>lista7.get(x).getRes_visit())
                    cont21 =cont21 + lista7.get(x).getRes_local();
                else
                    cont22 =cont22 + lista7.get(x).getRes_visit();
                
                if(lista8.get(x).getRes_local()<lista8.get(x).getRes_visit())
                    cont23 =cont23 + lista8.get(x).getRes_visit();
                else
                    cont24 =cont24 + lista8.get(x).getRes_local();
            }    
            PJL4.setText(String.valueOf(ProyectoESport.seleccionarResultadoPorLocal(lista.get(3).getId()).size()));
            PJV4.setText(String.valueOf(ProyectoESport.seleccionarResultadoPorVisitante(lista.get(3).getId()).size()));
            PL4.setText(String.valueOf(cont19));
            PV4.setText(String.valueOf(cont20));
            PGL4.setText(String.valueOf(cont21));
            PPL4.setText(String.valueOf(cont22));
            PGV4.setText(String.valueOf(cont23));
            PPV4.setText(String.valueOf(cont24));
            
            
            ArrayList<Partido> lista9 = ProyectoESport.seleccionarResultadoPorLocal(lista.get(4).getId());
            ArrayList<Partido> lista10 = ProyectoESport.seleccionarResultadoPorVisitante(lista.get(4).getId());
            for(int x=0;x<ProyectoESport.seleccionarResultadoPorLocal(lista.get(4).getId()).size();x++)
            {
                cont25 =cont25 + lista9.get(x).getRes_local();
                cont26 =cont26 + lista10.get(x).getRes_visit();
                if(lista9.get(x).getRes_local()>lista9.get(x).getRes_visit())
                    cont27 =cont27 + lista9.get(x).getRes_local();
                else
                    cont28 =cont28 + lista9.get(x).getRes_visit();
                
                if(lista10.get(x).getRes_local()<lista10.get(x).getRes_visit())
                    cont29 =cont29 + lista10.get(x).getRes_visit();
                else
                    cont30 =cont30 + lista10.get(x).getRes_local();
            }   
            PJL5.setText(String.valueOf(ProyectoESport.seleccionarResultadoPorLocal(lista.get(4).getId()).size()));
            PJV5.setText(String.valueOf(ProyectoESport.seleccionarResultadoPorVisitante(lista.get(4).getId()).size()));
            PL5.setText(String.valueOf(cont25));
            PV5.setText(String.valueOf(cont26));
            PGL5.setText(String.valueOf(cont27));
            PPL5.setText(String.valueOf(cont28));
            PGV5.setText(String.valueOf(cont29));
            PPV5.setText(String.valueOf(cont30));
            
            
            ArrayList<Partido> lista11 = ProyectoESport.seleccionarResultadoPorLocal(lista.get(5).getId());
            ArrayList<Partido> lista12 = ProyectoESport.seleccionarResultadoPorVisitante(lista.get(5).getId());
            for(int x=0;x<ProyectoESport.seleccionarResultadoPorLocal(lista.get(5).getId()).size();x++)
            {
                cont31 =cont31 + lista11.get(x).getRes_local();
                cont32 =cont32 + lista12.get(x).getRes_visit();
                if(lista11.get(x).getRes_local()>lista11.get(x).getRes_visit())
                    cont33 =cont33 + lista11.get(x).getRes_local();
                else
                    cont34 =cont34 + lista11.get(x).getRes_visit();
                
                if(lista12.get(x).getRes_local()<lista12.get(x).getRes_visit())
                    cont35 =cont35 + lista12.get(x).getRes_visit();
                else
                    cont36 =cont36 + lista12.get(x).getRes_local();
            }   
            PJL6.setText(String.valueOf(ProyectoESport.seleccionarResultadoPorLocal(lista.get(5).getId()).size()));
            PJV6.setText(String.valueOf(ProyectoESport.seleccionarResultadoPorVisitante(lista.get(5).getId()).size()));
            PL6.setText(String.valueOf(cont31));
            PV6.setText(String.valueOf(cont32));
            PGL6.setText(String.valueOf(cont33));
            PPL6.setText(String.valueOf(cont34));
            PGV6.setText(String.valueOf(cont35));
            PPV6.setText(String.valueOf(cont36));
            
            ArrayList<Partido> lista13 = ProyectoESport.seleccionarResultadoPorLocal(lista.get(6).getId());
            ArrayList<Partido> lista14 = ProyectoESport.seleccionarResultadoPorVisitante(lista.get(6).getId());
            for(int x=0;x<ProyectoESport.seleccionarResultadoPorLocal(lista.get(6).getId()).size();x++)
            {
                cont37 =cont37 + lista13.get(x).getRes_local();
                cont38 =cont38 + lista14.get(x).getRes_visit();
                if(lista13.get(x).getRes_local()>lista13.get(x).getRes_visit())
                    cont39 =cont39 + lista13.get(x).getRes_local();
                else
                    cont40 =cont40 + lista13.get(x).getRes_visit();
                
                if(lista14.get(x).getRes_local()<lista14.get(x).getRes_visit())
                    cont41 =cont41 + lista14.get(x).getRes_visit();
                else
                    cont42 =cont42 + lista14.get(x).getRes_local();
            }    
            PJL7.setText(String.valueOf(ProyectoESport.seleccionarResultadoPorLocal(lista.get(6).getId()).size()));
            PJV7.setText(String.valueOf(ProyectoESport.seleccionarResultadoPorVisitante(lista.get(6).getId()).size()));
            PL7.setText(String.valueOf(cont37));
            PV7.setText(String.valueOf(cont38));
            PGL7.setText(String.valueOf(cont39));
            PPL7.setText(String.valueOf(cont40));
            PGV7.setText(String.valueOf(cont41));
            PPV7.setText(String.valueOf(cont42));
            
            
            ArrayList<Partido> lista15 = ProyectoESport.seleccionarResultadoPorLocal(lista.get(7).getId());
            ArrayList<Partido> lista16 = ProyectoESport.seleccionarResultadoPorVisitante(lista.get(7).getId());
            for(int x=0;x<ProyectoESport.seleccionarResultadoPorLocal(lista.get(7).getId()).size();x++)
            {
                cont43 =cont43 + lista15.get(x).getRes_local();
                cont44 =cont44 + lista16.get(x).getRes_visit();
                if(lista15.get(x).getRes_local()>lista15.get(x).getRes_visit())
                    cont45 =cont45 + lista15.get(x).getRes_local();
                else
                    cont46 =cont46 + lista15.get(x).getRes_visit();
                
                if(lista16.get(x).getRes_local()<lista16.get(x).getRes_visit())
                    cont47 =cont47 + lista16.get(x).getRes_visit();
                else
                    cont48 =cont48 + lista16.get(x).getRes_local();
            } 
            PJL8.setText(String.valueOf(ProyectoESport.seleccionarResultadoPorLocal(lista.get(7).getId()).size()));
            PJV8.setText(String.valueOf(ProyectoESport.seleccionarResultadoPorVisitante(lista.get(7).getId()).size()));
            PL8.setText(String.valueOf(cont43));
            PV8.setText(String.valueOf(cont44));
            PGL8.setText(String.valueOf(cont45));
            PPL8.setText(String.valueOf(cont46));
            PGV8.setText(String.valueOf(cont47));
            PPV8.setText(String.valueOf(cont48));
            
            
        }
        catch(Exception e)
        {
        }
    }    
    
    private void bVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bVolverActionPerformed
        ProyectoESport.volverAtras(this);
    }//GEN-LAST:event_bVolverActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Clasificaciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Clasificaciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Clasificaciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Clasificaciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Clasificaciones().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField E1;
    private javax.swing.JTextField E2;
    private javax.swing.JTextField E3;
    private javax.swing.JTextField E4;
    private javax.swing.JTextField E5;
    private javax.swing.JTextField E6;
    private javax.swing.JTextField E7;
    private javax.swing.JTextField E8;
    private javax.swing.JTextField PGL1;
    private javax.swing.JTextField PGL2;
    private javax.swing.JTextField PGL3;
    private javax.swing.JTextField PGL4;
    private javax.swing.JTextField PGL5;
    private javax.swing.JTextField PGL6;
    private javax.swing.JTextField PGL7;
    private javax.swing.JTextField PGL8;
    private javax.swing.JTextField PGT1;
    private javax.swing.JTextField PGT2;
    private javax.swing.JTextField PGT3;
    private javax.swing.JTextField PGT4;
    private javax.swing.JTextField PGT5;
    private javax.swing.JTextField PGT6;
    private javax.swing.JTextField PGT7;
    private javax.swing.JTextField PGT8;
    private javax.swing.JTextField PGV1;
    private javax.swing.JTextField PGV2;
    private javax.swing.JTextField PGV3;
    private javax.swing.JTextField PGV4;
    private javax.swing.JTextField PGV5;
    private javax.swing.JTextField PGV6;
    private javax.swing.JTextField PGV7;
    private javax.swing.JTextField PGV8;
    private javax.swing.JTextField PJL1;
    private javax.swing.JTextField PJL2;
    private javax.swing.JTextField PJL3;
    private javax.swing.JTextField PJL4;
    private javax.swing.JTextField PJL5;
    private javax.swing.JTextField PJL6;
    private javax.swing.JTextField PJL7;
    private javax.swing.JTextField PJL8;
    private javax.swing.JTextField PJT1;
    private javax.swing.JTextField PJT2;
    private javax.swing.JTextField PJT3;
    private javax.swing.JTextField PJT4;
    private javax.swing.JTextField PJT5;
    private javax.swing.JTextField PJT6;
    private javax.swing.JTextField PJT7;
    private javax.swing.JTextField PJT8;
    private javax.swing.JTextField PJV1;
    private javax.swing.JTextField PJV2;
    private javax.swing.JTextField PJV3;
    private javax.swing.JTextField PJV4;
    private javax.swing.JTextField PJV5;
    private javax.swing.JTextField PJV6;
    private javax.swing.JTextField PJV7;
    private javax.swing.JTextField PJV8;
    private javax.swing.JTextField PL1;
    private javax.swing.JTextField PL2;
    private javax.swing.JTextField PL3;
    private javax.swing.JTextField PL4;
    private javax.swing.JTextField PL5;
    private javax.swing.JTextField PL6;
    private javax.swing.JTextField PL7;
    private javax.swing.JTextField PL8;
    private javax.swing.JTextField PPL1;
    private javax.swing.JTextField PPL2;
    private javax.swing.JTextField PPL3;
    private javax.swing.JTextField PPL4;
    private javax.swing.JTextField PPL5;
    private javax.swing.JTextField PPL6;
    private javax.swing.JTextField PPL7;
    private javax.swing.JTextField PPL8;
    private javax.swing.JTextField PPT1;
    private javax.swing.JTextField PPT2;
    private javax.swing.JTextField PPT3;
    private javax.swing.JTextField PPT4;
    private javax.swing.JTextField PPT5;
    private javax.swing.JTextField PPT6;
    private javax.swing.JTextField PPT7;
    private javax.swing.JTextField PPT8;
    private javax.swing.JTextField PPV1;
    private javax.swing.JTextField PPV2;
    private javax.swing.JTextField PPV3;
    private javax.swing.JTextField PPV4;
    private javax.swing.JTextField PPV5;
    private javax.swing.JTextField PPV6;
    private javax.swing.JTextField PPV7;
    private javax.swing.JTextField PPV8;
    private javax.swing.JTextField PT1;
    private javax.swing.JTextField PT2;
    private javax.swing.JTextField PT3;
    private javax.swing.JTextField PT4;
    private javax.swing.JTextField PT5;
    private javax.swing.JTextField PT6;
    private javax.swing.JTextField PT7;
    private javax.swing.JTextField PT8;
    private javax.swing.JTextField PV1;
    private javax.swing.JTextField PV2;
    private javax.swing.JTextField PV3;
    private javax.swing.JTextField PV4;
    private javax.swing.JTextField PV5;
    private javax.swing.JTextField PV6;
    private javax.swing.JTextField PV7;
    private javax.swing.JTextField PV8;
    private javax.swing.JButton bVolver;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
