/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controlador.ProyectoESport;
import javax.swing.JOptionPane;

/**
 *
 * @author sergio
 */
public class JornadasAdmin extends javax.swing.JFrame {

    /**
     * Creates new form JornadasAdmin
     */
    public JornadasAdmin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        EquipoLocal1 = new javax.swing.JTextField();
        EquipoLocal2 = new javax.swing.JTextField();
        EquipoLocal3 = new javax.swing.JTextField();
        ResultadoLocal1 = new javax.swing.JTextField();
        ResultadoLocal2 = new javax.swing.JTextField();
        ResultadoLocal3 = new javax.swing.JTextField();
        EquipoVisitante1 = new javax.swing.JTextField();
        EquipoVisitante2 = new javax.swing.JTextField();
        EquipoVisitante3 = new javax.swing.JTextField();
        ResultadoVisitante1 = new javax.swing.JTextField();
        ResultadoVisitante2 = new javax.swing.JTextField();
        ResultadoVisitante3 = new javax.swing.JTextField();
        NumJornada = new javax.swing.JTextField();
        bAnterior = new javax.swing.JButton();
        bSiguiente = new javax.swing.JButton();
        Jornada1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        EquipoLocal1.setBackground(new java.awt.Color(255, 255, 255));
        EquipoLocal1.setBorder(null);
        getContentPane().add(EquipoLocal1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 190, 210, 40));

        EquipoLocal2.setBackground(new java.awt.Color(255, 255, 255));
        EquipoLocal2.setBorder(null);
        getContentPane().add(EquipoLocal2, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 250, 210, 40));

        EquipoLocal3.setBackground(new java.awt.Color(255, 255, 255));
        EquipoLocal3.setBorder(null);
        getContentPane().add(EquipoLocal3, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 310, 210, 40));

        ResultadoLocal1.setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().add(ResultadoLocal1, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 190, 50, 40));

        ResultadoLocal2.setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().add(ResultadoLocal2, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 250, 50, 40));

        ResultadoLocal3.setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().add(ResultadoLocal3, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 310, 50, 40));

        EquipoVisitante1.setBackground(new java.awt.Color(255, 255, 255));
        EquipoVisitante1.setBorder(null);
        getContentPane().add(EquipoVisitante1, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 190, 210, 40));

        EquipoVisitante2.setBackground(new java.awt.Color(255, 255, 255));
        EquipoVisitante2.setBorder(null);
        getContentPane().add(EquipoVisitante2, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 250, 210, 40));

        EquipoVisitante3.setBackground(new java.awt.Color(255, 255, 255));
        EquipoVisitante3.setBorder(null);
        getContentPane().add(EquipoVisitante3, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 310, 210, 40));

        ResultadoVisitante1.setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().add(ResultadoVisitante1, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 190, 50, 40));

        ResultadoVisitante2.setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().add(ResultadoVisitante2, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 250, 50, 40));

        ResultadoVisitante3.setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().add(ResultadoVisitante3, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 310, 50, 40));

        NumJornada.setBackground(new java.awt.Color(153, 153, 0));
        NumJornada.setBorder(null);
        getContentPane().add(NumJornada, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 140, 180, 30));

        bAnterior.setText("Anterior");
        bAnterior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAnteriorActionPerformed(evt);
            }
        });
        getContentPane().add(bAnterior, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 130, 90, -1));

        bSiguiente.setText("Siguiente");
        bSiguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSiguienteActionPerformed(evt);
            }
        });
        getContentPane().add(bSiguiente, new org.netbeans.lib.awtextra.AbsoluteConstraints(1140, 130, -1, -1));

        Jornada1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Fotos/Jornadas.png"))); // NOI18N
        getContentPane().add(Jornada1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 130, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bAnteriorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAnteriorActionPerformed
         if (ProyectoESport.isAnterior())
        {
            // objeto
            String n=ProyectoESport.getAnteriorNombre();
            Integer e = ProyectoESport.getEdad();
            String p = ProyectoESport.getProfesion();
            String t=ProyectoESport.getTelefono();
            llenar(n,e,p,t);
        }
        else
            JOptionPane.showMessageDialog(this, " No hay más personas");
    
    }//GEN-LAST:event_bAnteriorActionPerformed

    private void bSiguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSiguienteActionPerformed
        if (ProyectoESport.isSiguiente())
        {
            String n=ProyectoESport.getSiguienteNombre();
            Integer e = ProyectoESport.getEdad();
            String p = ProyectoESport.getProfesion();
            String t=ProyectoESport.getTelefono();
            llenar(n,e,p,t);
        }
        else
            JOptionPane.showMessageDialog(this, " No hay más personas");
    }//GEN-LAST:event_bSiguienteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JornadasAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JornadasAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JornadasAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JornadasAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JornadasAdmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField EquipoLocal1;
    private javax.swing.JTextField EquipoLocal2;
    private javax.swing.JTextField EquipoLocal3;
    private javax.swing.JTextField EquipoVisitante1;
    private javax.swing.JTextField EquipoVisitante2;
    private javax.swing.JTextField EquipoVisitante3;
    private javax.swing.JLabel Jornada1;
    private javax.swing.JTextField NumJornada;
    private javax.swing.JTextField ResultadoLocal1;
    private javax.swing.JTextField ResultadoLocal2;
    private javax.swing.JTextField ResultadoLocal3;
    private javax.swing.JTextField ResultadoVisitante1;
    private javax.swing.JTextField ResultadoVisitante2;
    private javax.swing.JTextField ResultadoVisitante3;
    private javax.swing.JButton bAnterior;
    private javax.swing.JButton bSiguiente;
    // End of variables declaration//GEN-END:variables
}
