CREATE OR REPLACE FUNCTION VICTORIAS_TOTALES
(NEQUIPO IN EQUIPO.NOMBRE%TYPE)
RETURN NUMBER
IS
V_VISITANTE NUMBER;
V_LOCAL NUMBER;
CANTIDAD NUMBER;
BEGIN

    SELECT MAX(COUNT(*)) INTO V_VISITANTE
    FROM VICTORIAS_VISITANTE
    WHERE NOMBRE_EQUIPO=NEQUIPO
    GROUP BY NOMBRE_EQUIPO;

    SELECT MAX(COUNT(*)) INTO V_LOCAL
    FROM VICTORIAS_LOCAL
    WHERE NOMBRE_EQUIPO=NEQUIPO
    GROUP BY NOMBRE_EQUIPO;
    
    CANTIDAD:=V_LOCAL+V_VISITANTE;
    
    RETURN CANTIDAD;
END;