CREATE OR REPLACE VIEW Persona(NOMBRE, NICK, SUELDO, AÑOS_DUEÑO, NOMBRE_EQUIPO)
AS
SELECT P.NOMBRE, P.NICK, P.SUELDO, D.ANIOS_DUEINO, E.NOMBRE
FROM PERSONAS P, DUEINO D, EQUIPO E
WHERE P.ID_EQUIPO=E.ID
AND P.ID=D.IDD
WITH READ ONLY;