CREATE OR REPLACE VIEW VICTORIAS_LOCAL (RESULTADO_LOCAL, NOMBRE_EQUIPO)
AS
SELECT P.RESULTADO_LOCAL, E.NOMBRE
FROM PARTIDO P, EQUIPO E
WHERE P.RESULTADO_LOCAL>P.RESULTADO_VISITANTE
AND P.ID_LOCAL=E.ID
WITH READ ONLY; 