CREATE OR REPLACE VIEW ENTRENADORES (NOMBRE, NICK, SUELDO, MAIL, NOMBRE_EQUIPO)
AS
SELECT P.NOMBRE, P.NICK, P.SUELDO, N.MAIL, E.NOMBRE
FROM PERSONAS P, ENTRENADOR N, EQUIPO E
WHERE P.ID_EQUIPO=E.ID
AND P.ID=N.IDE
WITH READ ONLY;