CREATE OR REPLACE VIEW DERROTAS_VISITANTE (RESULTADO_VISITANTE, NOMBRE_EQUIPO)
AS
SELECT P.RESULTADO_VISITANTE, E.NOMBRE
FROM PARTIDO P, EQUIPO E
WHERE P.RESULTADO_LOCAL>P.RESULTADO_VISITANTE
AND P.ID_VISITANTE=E.ID;