/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Vista;

/**
 *
 * @author 1gdaw03
 */
public class DatosEquipos extends javax.swing.JFrame {

    /** Creates new form DatosEquipos */
    public DatosEquipos() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        tfEntrenadorEquipo = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        tfAsistenteEquipo = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        tfDueñoEquipo = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        tfIDCal = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        tfPuntosEquipo = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        tfPaginaWeb = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        tfNombreE = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        tfIDE = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        taJugadoresEquipo = new javax.swing.JTextArea();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("ID_Equipo");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 70, 79, -1));
        getContentPane().add(tfEntrenadorEquipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 590, 329, -1));

        jLabel2.setText("Nombre");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 140, 79, -1));
        getContentPane().add(tfAsistenteEquipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 520, 329, -1));

        jLabel3.setText("PaginaWeb");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 220, 79, -1));
        getContentPane().add(tfDueñoEquipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 440, 329, -1));

        jLabel4.setText("Puntos");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 290, 79, -1));
        getContentPane().add(tfIDCal, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 370, 329, -1));

        jLabel5.setText("ID_Calendario");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 370, -1, -1));
        getContentPane().add(tfPuntosEquipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 290, 329, -1));

        jLabel6.setText("Dueño");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 450, 79, -1));
        getContentPane().add(tfPaginaWeb, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 210, 329, -1));

        jLabel7.setText("Asistente");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 520, 79, -1));
        getContentPane().add(tfNombreE, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 140, 329, -1));

        jLabel8.setText("Entrenador");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 600, 79, -1));
        getContentPane().add(tfIDE, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 60, 329, -1));

        jLabel9.setText("Jugadores");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 670, 79, -1));

        jButton1.setText("Atras");
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 670, 83, 44));

        taJugadoresEquipo.setColumns(20);
        taJugadoresEquipo.setRows(5);
        jScrollPane1.setViewportView(taJugadoresEquipo);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 670, 329, 184));

        jLabel10.setIcon(new javax.swing.ImageIcon("C:\\Users\\1GDAW01\\Downloads\\54362.jpg")); // NOI18N
        jLabel10.setText("jLabel10");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(-300, -260, -1, 1170));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DatosEquipos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DatosEquipos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DatosEquipos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DatosEquipos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DatosEquipos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea taJugadoresEquipo;
    private javax.swing.JTextField tfAsistenteEquipo;
    private javax.swing.JTextField tfDueñoEquipo;
    private javax.swing.JTextField tfEntrenadorEquipo;
    private javax.swing.JTextField tfIDCal;
    private javax.swing.JTextField tfIDE;
    private javax.swing.JTextField tfNombreE;
    private javax.swing.JTextField tfPaginaWeb;
    private javax.swing.JTextField tfPuntosEquipo;
    // End of variables declaration//GEN-END:variables

}
